grammar-and-gender
openSUSE/openSUSE-release-tools pull request #2551
Opened 2021-04-14 15:07 UTC by gonyere

gendered terms, and some minor grammar edits, mostly along with them, but a few others nearby as well

2021-04-14 15:28 UTC, coolo requested changes
Thanks for the feedback. I found some typos though.

And I'm happy that you didn't find any assumed male roles :)

One more thing: Please use a little more descriptive commit log - what you wrote as PR summary would do.

2021-04-14 15:28 UTC, coolo commented on docs/check_source.asciidoc
> +The program will als search some external scripts (like
this looks a missing o

2021-04-14 15:28 UTC, coolo commented on docs/staging.asciidoc
> +in a staging project, this request is review inside th project.
this looks a missing e

2021-04-14 15:28 UTC, coolo commented on docs/staging.asciidoc
> +An\ staging project is a mere project linked to a subset of Factory
Has this backslash a significance?

2021-04-14 15:28 UTC, coolo commented on docs/testing.asciidoc
> +Each object is contains functions for the individual tests so split them per
the is looks too much now

2021-04-14 17:48 UTC, gonyere commented
Hi, thanks for the comments! I'm kinda new at this, I'll make sure my commit log is more descriptive next time!

2021-04-16 13:29 UTC, coolo commented
Can you please fix the typo in check_source? Then I can merge this

2021-04-20 11:02 UTC, gonyere reviewed
fixed also

2021-04-20 11:56 UTC, merged