Perl linter
openSUSE/openSUSE-release-tools pull request #2586
Opened 2021-07-01 20:04 UTC by jreidinger

Is that check_source.pl used at all? Some bugs in it looks bad enough, especially that regexp.

2021-07-01 20:44 UTC, jreidinger commented
Too make this work it needs to adapt test docker container to contain also all required perl libraries.

2021-07-02 03:53 UTC, coolo commented
Yes, check_source.pl is used by check_source.py (just to add to the fun of it :)

And that regexp bug isn't as bad as it first looks - it just means we also look for patches mentioned in other parts of the diff, not just the + part. I guess this leads to 0 problems in reality - but good catch anyway.

2021-07-02 03:56 UTC, coolo commented
And the CI container is defined in `dist/ci/testenv-tumbleweed/Dockerfile` - but I just learned it's broken:
https://build.opensuse.org/package/show/openSUSE:Tools:Images/osrt-testenv-tumbleweed

2021-07-02 06:14 UTC, jreidinger commented
@coolo thanks, I will check it and try fix that container.

2021-07-02 06:55 UTC, coolo commented
Fixed the container in OBS - the problem was an inconsistent file provides between Factory and openSUSE:Tools:Images

2021-07-09 06:16 UTC, coolo requested changes

2021-07-09 06:16 UTC, coolo commented on .perl_checker.sh
> +for i in `find . | grep 'p[lm]$'`; do
please no hidden files as commands. We have dist/ci for that

2021-07-09 06:28 UTC, coolo approved these changes

2021-07-09 06:50 UTC, merged

2021-09-21 08:27 UTC, DimStar77 commented
> Yes, check_source.pl is used by check_source.py (just to add to the fun of it :)
> 
> And that regexp bug isn't as bad as it first looks - it just means we also look for patches mentioned in other parts of the diff, not just the + part. I guess this leads to 0 problems in reality - but good catch anyway.

The SLE submissions actually relied on this bug

i.e:
* a patch is added in SLE-SP-(n-1), referenced in the changelog, as is needed.
* in SLE-SP-n, the package is taken from Factory, which never had the patch. The diff now shows the patch being 'lost', which was considered ok (the changelog never mentions the patch being added, so we also do not drop it in the changelog)
* So, the fix is technically seen correct, but causes more issues for SLE now - as patches can't formally be 'lost' anymore

2021-09-21 08:34 UTC, DimStar77 commented
The above note is also a problem for TW-proper: if I have to submit a 'revert submission SR', then patches are being dropped the same way (i.e. never added) - the bot would now decline those too

2021-09-21 08:37 UTC, coolo commented
Well, then this should be properly implemented not rely on a bug

2021-09-21 08:41 UTC, DimStar77 commented
> Well, then this should be properly implemented not rely on a bug

Of course - I wasn't trying to imply we should put the bug back in place. Just that the bug was unnoticed for a long time and 'served us well'

2021-09-21 08:50 UTC, suntorytimed commented
Agreeing with DimStar77 and coolo, we should not rely on a bug for this. Nevertheless we require a proper implementation sooner than later, as this will hit us with a couple of submissions to SLE. I have opened a bug and linked it to this PR.