staging: consider first staging a target even without --move
openSUSE/openSUSE-release-tools pull request #2700
Opened 2022-02-16 15:29 UTC by DimStar77

Fixes #2699

2022-02-16 15:31 UTC, DimStar77 commented
With this, I could do 'Staging select D rook':

```
> osc staging select D rook
(1/1) Adding request "955388" to project "openSUSE:Factory:Staging:D"
```

merging adi:

```
> osc staging select adi:15 --move adi:24
(1/1) Moving "955345" from "openSUSE:Factory:Staging:adi:24" to "openSUSE:Factory:Staging:adi:15"
```

If specifying a 2nd adi without move, it is interpreted as a package name:

```
> osc staging select adi:15 adi:24
No SR# found for: adi:24
```

which sounds acceptable

2022-02-16 18:58 UTC, coolo commented
The fix is wrong. Not sure when this was used for the last time, but the use case back then was "staging select D E" and then it would picked a strategy to shuffle between D and E

2022-02-16 19:04 UTC, DimStar77 commented
> The fix is wrong. Not sure when this was used for the last time, but the use case back then was "staging select D E" and then it would picked a strategy to shuffle between D and E

oh - those ominous strategies... the problem is that the current code is even worse than the broken (unused) strategies..

What would be the correct fix in your opinion?

something like:

```
if arg in existing_stagings and arg not in stagings and ((len(stagings) == 0 and opts.move) or not opts.move):
       stagings.append(api.extract_staging_short(arg))
```

?

2022-02-16 20:32 UTC, coolo commented
yes, good thinking. Now if you convert that de morgan style you end up with `and not ((opts.move or len(stagings) > 0) and opts.move)`. Now opts.move is both and and or, so reduce it to and and you'll get `and not (opts.move and len(stagings) > 0)`

So: we want to skip adding staging if we have move and it's the 1+ staging. Easy, eh? :)

To be honest I had the feeling the condition is wrong, but in the examples I tried it worked, so I though my feeling is wrong.

2022-02-16 20:34 UTC, coolo requested changes

2022-02-16 20:34 UTC, coolo commented on osc-staging.py
> +                if arg in existing_stagings and arg not in stagings and (len(stagings) == 0):
```suggestion
               if arg in existing_stagings and arg not in stagings and not (len(stagings) > 0 and opts.move)
```

2022-02-17 08:15 UTC, coolo approved these changes

2022-02-17 08:15 UTC, merged