Add support to containerfile repo to SLE15
openSUSE/openSUSE-release-tools pull request #2806
Opened 2022-04-22 11:39 UTC by gyr

2022-04-28 12:25 UTC, Vogtinator requested changes
`SUSE:SLE-15-SP4:GA:TEST/containerfile` got renamed to `containers`

For consistency, `sles15-image` should be released into `SUSE:SLE-15-SP4:GA:TEST/containers` as well, that needs to be done explicitly as the other images still go to the default release target.

2022-04-28 12:27 UTC, Vogtinator requested changes
Looks like it's missing the part for `Release.Images.To.Publish` as well

2022-04-28 13:23 UTC, Vogtinator commented on gocd/sp4.target.gocd.yaml
> +            CONTAINERS=$(osc -A https://api.suse.de results -b -s succeeded SUSE:SLE-15-SP4:GA -r containerfile | cut -f1 -d ' '| uniq)
I'm a bit suspicious of the `-s succeeded`. Images without that would silently be skipped. There could be a race between the check above and now...

2022-05-06 08:21 UTC, vasiliy-ul commented
Hey, ping here. @Vogtinator , do you think this is now good to go?  Can we move it forward?

2022-05-06 08:24 UTC, Vogtinator commented
> Hey, ping here. @Vogtinator , do you think this is now good to go? Can we move it forward?

It's on my todo list, I'll have a look later

2022-05-06 11:32 UTC, Vogtinator requested changes

2022-05-06 11:32 UTC, Vogtinator commented on gocd/sp4.target.gocd.yaml
> +            osc -A https://api.suse.de release SUSE:SLE-15-SP4:GA sles15-image --target-project=containers
I think this needs

```suggestion
            osc -A https://api.suse.de release --target-project=SUSE:SLE-15-SP4:GA --target-repository=containers -r images SUSE:SLE-15-SP4:GA sles15-image
```

2022-05-06 11:32 UTC, Vogtinator commented on gocd/sp4.target.gocd.yaml
> +                  osc -A https://api.suse.de release SUSE:SLE-15-SP4:GA sles15-image --target-project=containers
Same as above

2022-05-09 14:06 UTC, gyr commented on gocd/sp4.target.gocd.yaml
> +                  osc -A https://api.suse.de release SUSE:SLE-15-SP4:GA sles15-image --target-project=containers
Fixed

2022-05-10 15:08 UTC, Vogtinator approved these changes
Let's see whether it also works in practice

2022-05-10 15:46 UTC, merged

2022-05-11 19:47 UTC, suntorytimed commented
Looks like it fails. The to test is now releasing all packages to images. So all of standard is being released to TEST in images.