Retab publish distro
openSUSE/openSUSE-release-tools pull request #2906
Opened 2022-12-12 13:19 UTC by lkocman

* based on https://github.com/openSUSE/openSUSE-release-tools/pull/2903#discussion_r1035751458
    * retab with ts=4,et
    * supply vim modeline

2022-12-12 13:48 UTC, mvidner requested changes
I'd like to point out that https://github.com/openSUSE/openSUSE-release-tools/blob/master/.editorconfig exists and says that `*` files (shell) use 2 spaces
Your choice of 4 spaces is inconsistent :)

2022-12-13 12:23 UTC, lkocman commented
> I'd like to point out that https://github.com/openSUSE/openSUSE-release-tools/blob/master/.editorconfig exists and says that `*` files (shell) use 2 spaces Your choice of 4 spaces is inconsistent :)

Force pushed with two tabs instead

2022-12-14 21:01 UTC, dirkmueller commented on publish_distro
> +# vim:sw=4:ts=4:et:
That now needs updating or removal

2022-12-14 21:01 UTC, dirkmueller requested changes
See inline comment

2023-01-02 18:47 UTC, coolo commented
Superseded by #2910 (fixing the editor config conformance for all)

2023-01-02 18:47 UTC, closed without merging