Don't abort if weakremover.inc don't exist on source project
openSUSE/openSUSE-release-tools pull request #3049
Opened 2024-01-23 13:35 UTC by fcrozat

For ALP, weakremover.inc might not be part of the staging parent project. Just ignore 404 error in that case.

2024-01-23 13:39 UTC, Vogtinator requested changes
IMO this needs explicit error handling for all possible cases:

(exists in staging, doesn't exist in staging) * (exists in target project, doesn't exist in target project)

In the case that there's a mismatch I'm not sure what it should do though. IMO abort and ask the user to resolve it manually.

Currently it silently ignores any possible errors which is bad.

2024-02-09 14:34 UTC, Vogtinator approved these changes
Should ideally check for 404 but it didn't do that before either :shrug:

2024-05-07 14:35 UTC, Vogtinator commented on osclib/freeze_command.py
> +            sourceurlurl_exists=False
```suggestion
            sourceurl_exists=False
```

2024-05-14 08:45 UTC, Vogtinator approved these changes

2024-05-15 14:06 UTC, Vogtinator commented
I'd merge, but now there are unrelated commits on top

2024-05-15 14:39 UTC, fcrozat commented
> I'd merge, but now there are unrelated commits on top

let me fix that, I should have used a topic branch in the first place..

2024-05-15 15:02 UTC, fcrozat commented
switching to https://github.com/openSUSE/openSUSE-release-tools/pull/3083

2024-05-15 15:02 UTC, closed without merging